import type { ColumnType, Generated, Insertable, Selectable, Updateable } from "kysely";

export type Database = {
    parents: ParentsTable;
    students: StudentsTable;
    student_parents: StudentParentsTable;
    projects: ProjectsTable;
    project_daily_reports: ProjectDailyReportsTable;
    materials: MaterialsTable;
    project_materials: ProjectMaterialsTable;
    daily_report_tags: DailyReportTagsTable;
    daily_report_tag_usages: DailyReportTagUsagesTable;
    trips: TripsTable;
    student_trips: StudentTripsTable;
};

export default Database;

// This interface describes the `parent` table to Kysely. Table
// interfaces should only be used in the `Database` type above
// and never as a result type of a query!. See the `Parent`,
// `NewParent` and `ParentUpdate` types below.
export interface ParentsTable {
    // Columns that are generated by the database should be marked
    // using the `Generated` type. This way they are automatically
    // made optional in inserts and updates.
    id: Generated<number>;

    name: string;
    birthday: Date;

    // If the column is nullable in the database, make its type nullable.
    // Don't use optional properties. Optionality is always determined
    // automatically by Kysely.
    favorite_color: string | null;
    email: string | null;
    phone: string | null;
    secret: string | null;

    // You can specify a different type for each operation (select, insert and
    // update) using the `ColumnType<SelectType, InsertType, UpdateType>`
    // wrapper. Here we define a column `created_at` that is selected as
    // a `Date`, can optionally be provided as a `string` in inserts and
    // can never be updated:
    created_at: ColumnType<Date, string | undefined, never>;

    updated_at: ColumnType<Date, string | undefined, never>;
}

// You should not use the table schema interfaces directly. Instead, you should
// use the `Selectable`, `Insertable` and `Updateable` wrappers. These wrappers
// make sure that the correct types are used in each operation.
//
// Most of the time you should trust the type inference and not use explicit
// types at all. These types can be useful when typing function arguments.
export type Parent = Selectable<ParentsTable>;
export type NewParent = Insertable<ParentsTable>;
export type ParentUpdate = Updateable<ParentsTable>;

export interface StudentsTable {
    id: Generated<number>;
    name: string;
    created_at: ColumnType<Date, string | undefined, never>;
    updated_at: ColumnType<Date, string | undefined, never>;
    student_number: string;
}
export type Student = Selectable<StudentsTable>;
export type NewStudent = Insertable<StudentsTable>;
export type StudentUpdate = Updateable<StudentsTable>;

export interface StudentParentsTable {
    id: Generated<number>;
    student_id: number;
    parent_id: number;
    created_at: ColumnType<Date, string | undefined, never>;
    updated_at: ColumnType<Date, string | undefined, never>;
}
export type StudentParent = Selectable<StudentParentsTable>;
export type NewStudentParent = Insertable<StudentParentsTable>;
export type StudentParentUpdate = Updateable<StudentParentsTable>;

export interface ProjectsTable {
    id: Generated<number>;
    name: string;
    description: string | null;
    status: string;
    address: string | null;
    start_date: ColumnType<Date, string | undefined, string | undefined>;
    end_date: ColumnType<Date, string | undefined, string | undefined> | null;
    budget: number | null;
    created_at: ColumnType<Date, string | undefined, never>;
    updated_at: ColumnType<Date, string | undefined, never>;
}
export type Project = Selectable<ProjectsTable>;
export type NewProject = Insertable<ProjectsTable>;
export type ProjectUpdate = Updateable<ProjectsTable>;

export interface ProjectDailyReportsTable {
    id: Generated<number>;
    project_id: number;
    report_date: ColumnType<Date, string, string>;
    summary: string;
    summary_embedding: number[];
    photo_file_name: string | null;
    created_at: ColumnType<Date, string | undefined, never>;
    updated_at: ColumnType<Date, string | undefined, never>;
}
export type ProjectDailyReport = Selectable<ProjectDailyReportsTable>;
export type NewProjectDailyReport = Insertable<ProjectDailyReportsTable>;
export type ProjectDailyReportUpdate = Updateable<ProjectDailyReportsTable>;

export interface MaterialsTable {
    id: Generated<number>;
    name: string;
    description: string | null;
    category: string;
    unit: string;
    unit_cost: number | null;
    created_at: ColumnType<Date, string | undefined, never>;
    updated_at: ColumnType<Date, string | undefined, never>;
}
export type Material = Selectable<MaterialsTable>;
export type NewMaterial = Insertable<MaterialsTable>;
export type MaterialUpdate = Updateable<MaterialsTable>;

export interface ProjectMaterialsTable {
    id: Generated<number>;
    project_id: number;
    daily_report_id: number;
    material_id: number;
    quantity: ColumnType<string, string | number, string | number>;
    notes: string | null;
    created_at: ColumnType<Date, string | undefined, never>;
    updated_at: ColumnType<Date, string | undefined, never>;
}
export type ProjectMaterial = Selectable<ProjectMaterialsTable>;
export type NewProjectMaterial = Insertable<ProjectMaterialsTable>;
export type ProjectMaterialUpdate = Updateable<ProjectMaterialsTable>;

export interface DailyReportTagsTable {
    id: Generated<number>;
    name: string;
    created_at: ColumnType<Date, string | undefined, never>;
    updated_at: ColumnType<Date, string | undefined, never>;
}
export type DailyReportTag = Selectable<DailyReportTagsTable>;
export type NewDailyReportTag = Insertable<DailyReportTagsTable>;
export type DailyReportTagUpdate = Updateable<DailyReportTagsTable>;

export interface DailyReportTagUsagesTable {
    id: Generated<number>;
    daily_report_id: number;
    daily_report_tag_id: number;
    created_at: ColumnType<Date, string | undefined, never>;
    updated_at: ColumnType<Date, string | undefined, never>;
}
export type DailyReportTagUsage = Selectable<DailyReportTagUsagesTable>;
export type NewDailyReportTagUsage = Insertable<DailyReportTagUsagesTable>;
export type DailyReportTagUsageUpdate = Updateable<DailyReportTagUsagesTable>;

export interface TripsTable {
    id: Generated<number>;
    destination: string;
    date: ColumnType<Date, string | Date | undefined, string | Date | undefined>;
    created_at: ColumnType<Date, string | undefined, never>;
    updated_at: ColumnType<Date, string | undefined, never>;
}
export type Trip = Selectable<TripsTable>;
export type NewTrip = Insertable<TripsTable>;
export type TripUpdate = Updateable<TripsTable>;

export interface StudentTripsTable {
    id: Generated<number>;
    student_id: number;
    trip_id: number;
    approved: boolean | null;
    approved_by_parent_id: number | null;
    created_at: ColumnType<Date, string | undefined, never>;
    updated_at: ColumnType<Date, string | undefined, never>;
}
export type StudentTrip = Selectable<StudentTripsTable>;
export type NewStudentTrip = Insertable<StudentTripsTable>;
export type StudentTripUpdate = Updateable<StudentTripsTable>;
